baseURL = "https://128bit.io"
languageCode = "en-us"
title = "128bit.io"
copyright = "&copy; <a href=\"https://github.com/amscotti\">Anthony Scotti</a> 2020"
theme = "kiss"
Paginate = 7 # Number of posts per page
enableRobotsTXT = true

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "128bit.io" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks

[params.social]
twitter = "amscotti"
github = "amscotti"
email = "anthony@128bit.io"
linkedin = "amscotti"
instagram = "anthony_scotti"

[params.social.config]
platforms = ["github","twitter","instagram","email","linkedin"]

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true